### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ksegaba** [evojgani/EpiGP#1]
Hello, I am trying to install the miraculix and RandomFieldsUtils packages through RStudio and I am coming across the error: 
Error: Failed to install 'RandomFieldsUtils' from local:
  (converted from warning) installation of package ‘/var/folders/07/42cmd3lx161_xzxm_v2dz1280000gn/T//Rtmp0DFtfR/file620f5dcb17a0/RandomFieldsUtils_0.5.9.tar.gz’ had non-zero exit status
  
I have done some searching online for different ways to install .tar.gz packages and have tried the following but continue to get the errors:
install.packages("RandomFieldsUtils_0.5.9.tar.gz", repos=NULL)
devtools::install_local("RandomFieldsUtils_0.5.9.tar.gz")

I've even tried Tools > Install Packages... in RStudio, but no luck.

I believe I was successful in opening the EpiGP R project by using the command openProject command, though.
rstudioapi::openProject("/Users/keniasegura/evojgani-EpiGP-c5761a1/pkg/EpiGP.Rproj")

Thank you and I appreciate your time.

**Comment by evojgani** [comment]
Hello,

What kind of errors do you have? Do you use their source files for installing?

Best Regards,
Elaheh Vojgani

From: Kenia Segura Abá ***@***.***
Sent: Friday, July 23, 2021 6:33 PM
To: evojgani/EpiGP
Cc: Subscribed
Subject: [evojgani/EpiGP] Installation issues (#1)


Hello, I am trying to install the miraculix and RandomFieldsUtils packages through RStudio and I coming across the error:

**Comment by ksegaba** [comment]
Hello,

I was getting the error I specified on the GitHub issue, but I eventually
figured out how to install everything by running the below:

unzip("EpiGP-v0.1.0.zip")
devtools::install_local("evojgani-EpiGP-c5761a1/miraculix_0.9.6.tar.gz")
devtools::install_local("evojgani-EpiGP-c5761a1/RandomFieldsUtils_0.5.9.tar.gz")
devtools::install_local("evojgani-EpiGP-c5761a1/pkg/")

I'm not sure why devtools wasn't working before on my localhost. But,
whenever I tried it on the RStudio that's hosted on the HPC, it worked for
me.

Best,
Kenia Segura
